#include <stdio.h>

#include "../context.h"
#include "../errors.h"

#ifdef _WIN64
int BF_compile_context(BF_Context *ctx, const char *output_file)
{
  if (!ctx) return BF_ERR_INVALID_PARAM;
  
  int test = BF_test_context(ctx);
  if (test) return test;

  FILE *out = fopen(output_file, "w+");
  if (!out) return BF_ERR_COULD_NOT_OPEN_FILE;

  fprintf(
    out,
    "# gas x64 windowsNT\n"
    "# generated by whyis2plus2's brainfuck compiler\n"
    "# requires kernel32.dll when linking\n"
    ".global mainCRTStartup\n\n"
    ".text\n"
    ".lcomm input_buffer, 8\n"
    ".lcomm input_len, 2\n\n"
    "mainCRTStartup:\n"
    "\tpush %%rbp\n"
    "\tmovq %%rsp, %%rbp\n"
    "\tmovq $0, %%rcx\n"
    "\tmovq $%zu, %%rdx\n"
    "\tmovq $0x3000, %%r8\n"
    "\tmovq $4, %%r9\n"
    "\tcall VirtualAlloc\n"
    "\tmovq %%rax, %%r12\n"
    "\tleaq %zu(%%r12), %%rax\n"
    "\tmovq %%rax, input_buffer(%%rip)\n",
    ctx->num_cells + 4096, // 4096 is the size of the io buffer
    ctx->num_cells
  );

  for (size_t i = 0; i < ctx->tokens.len; ++i) {
    // printf("Token: %s\n", BF_get_token_name(ctx.tokens.data[i]));
    const BF_Token tok = ctx->tokens.data[i];

    switch (tok.type) {
      case BF_NUM_TOKEN_TYPES:
      case BF_TOK_NONE: break;

      case BF_TOK_ARITH:
        fprintf(out, "\taddb $%u, (%%r12)\n", tok.arith.amount);
        break;

      case BF_TOK_MOVIDX:
        fprintf(out, "\taddq $%zu, %%r12\n", tok.mov_idx.amount);
        break;

      case BF_TOK_BEGIN_LOOP:
        BF_jump_list_push(&ctx->loops, i);
        fprintf(out, ".Lloop_%zu:\n", i);
        break;

      case BF_TOK_END_LOOP:
        fprintf(
          out,
          "\tcmpb $0, (%%r12)\n"
          "\tjne .Lloop_%zu\n",
          ctx->loops.indicies[ctx->loops.len - 1]
        );

        --ctx->loops.len;
        break;
      
      case BF_TOK_PRINT:
        fprintf(
          out, 
          "\tmovb (%%r12), %%cl\n"
          "\tcall write_char\n"
        );

        break;

      case BF_TOK_INPUT:
        fprintf(
          out,
          "\tmovq %%r12, %%rcx\n"
          "\tcall read_char\n"
        );

        break;
    }
  }

  fprintf(
    out,
    "\txorq %%rcx, %%rcx\n"
    "\tcall ExitProcess\n\n"
    "# helper functions\n"
    "read_char:\n"
    "\tpush %%rbp\n"
    "\tmovq %%rsp, %%rbp\n"
    "\tsubq $48, %%rsp\n"
    "\tmovq %%rcx, -8(%%rbp)\n"
    "\tcmpq $2, input_len(%%rip)\n"
    "\tjl .Lread_char_buf_empty\n"
    "\tdecq input_len(%%rip)\n"
    "\tincq input_buffer(%%rip)\n"
    "\tmovq input_buffer(%%rip), %%rdx\n"
    "\tmovq -8(%%rbp), %%rcx\n"
    "\tmovb (%%rdx), %%dl\n"
    "\tmovb %%dl, (%%rcx)\n"
    "\tjmp .Lread_char_ret\n"
    ".Lread_char_buf_empty:\n"
    "\tmovq $-10, %%rcx\n"
    "\tcall GetStdHandle\n"
    "\tmovq %%rax, %%rcx\n"
    "\tmovq input_buffer(%%rip), %%rdx\n"
    "\tmovq $4096, %%r8\n"
    "\tleaq -16(%%rbp), %%r9\n"
    "\tmovq input_buffer(%%rip), %%rax\n"
    "\tmovq %%rax, 16(%%rsp)\n"
    "\tcall ReadFile\n"
    "\tmovq -8(%%rbp), %%rcx\n"
    "\tmovq input_buffer(%%rip), %%rax\n"
    "\tmovb (%%rax), %%dl\n"
    "\tmovb %%dl, (%%rcx)\n"
    "\tmovq -16(%%rbp), %%rax\n"
    "\tmovq %%rax, input_len(%%rip)\n"
    "\tsubq $2, input_len(%%rip)\n"
    ".Lread_char_ret:\n"
    "\tleave\n"
    "\tret\n\n"
    "write_char:\n"
    "\tpush %%rbp\n"
    "\tmovq %%rsp, %%rbp\n"
    "\tsub $48, %%rsp\n"
    "\tmovb %%cl, -8(%%rbp)\n"
    "\tmovq $-11, %%rcx\n"
    "\tcall GetStdHandle\n"
    "\tmovq %%rax, %%rcx\n"
    "\tleaq -8(%%rbp), %%rdx\n"
    "\tmovq $1, %%r8\n"
    "\txorq %%r9, %%r9\n"
    "\tmovq $0, -16(%%rbp)\n"
    "\tcall WriteFile\n"
    "\tleave\n"
    "\tret\n"
  );

  fclose(out);
  return 0;
}
#endif
